---
title: "Survival Analysis"
output: html_document
date: "2026-01-25"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(survminer)
library(survMisc)
library(ggplot2)
library(dplyr)
library(lubridate)
library(ggsurvfit)
library(tidycmprsk)
library(tidyr)
```

#Data Set Up
```{r, echo = FALSE, message = FALSE, warning = FALSE}
data_path = "C:/Bre/SONOMA/Sonoma_cleaned.csv"

clean_s = read.csv(data_path, check.names = FALSE, row.names=1) 

#subsetting data to just NOM patients
NOM_patients <- clean_s[clean_s$initial_planoutcomes == 2,] 

NOM_patients <- NOM_patients[!is.na(NOM_patients$time_of_dxoutcomes),] #removing NA values for date/time of patients dx of appendicitis
#sum(is.na(NOM_patients$time_of_dxoutcomes)) #looking for NAs
NOM_patients$time_of_dxoutcomes <- gsub(" .*","", NOM_patients$time_of_dxoutcomes) #removing time part of date/time
#sum(is.na(NOM_patients$time_of_dxoutcomes)) #checking for NAs again

#converting date_index to date object


NOM_patients$time_of_dxoutcomes <- ymd(NOM_patients$time_of_dxoutcomes)


#converting date of appendectomy after NOM to date object, converting blanks to NAs
NOM_patients$appy_int_dateoutcomes[
  NOM_patients$appy_int_dateoutcomes == ""
] <- NA

NOM_patients$appy_int_dateoutcomes <- ymd(NOM_patients$appy_int_dateoutcomes)


#creating variable that is time in days from NOM decision to appy
NOM_patients$time_to_appy <- NOM_patients$appy_int_dateoutcomes - NOM_patients$time_of_dxoutcomes
#I thought they were only followed for a year after, but many of these times look way past 365 days so what time for censored individuals?

#DONT NEED THIS IF WE GET NEW TIMES FOR TWO ERRORS
NOM_patients <- NOM_patients[NOM_patients$time_to_appy > 0 | is.na(NOM_patients$time_to_appy), ] #DONT NEED THIS IF WE GET NEW TIMES


#setting NA values to 0 for censored, creating status variable for survival
NOM_patients$status <- ifelse(
  is.na(NOM_patients$interval_typeoutcomes),
  0,   # censored
  NOM_patients$interval_typeoutcomes
)



NOM_patients$status <- as.numeric(NOM_patients$status)



#creating time_to_event for all NOM patients, making it 365 for censored individuals
NOM_patients$time_to_event <- ifelse(
  is.na(NOM_patients$time_to_appy),
  365,
  NOM_patients$time_to_appy
)
#administratively censoring those beyond 1 year
NOM_patients$status365 <- ifelse(
  NOM_patients$time_to_event > 365, 
  0, #administratively censored beyond 1 year
  NOM_patients$status
)

#changing time to event to 365 days for censored beyond 1 year individuals
NOM_patients$time_to_event <- ifelse(
  NOM_patients$status365 == 0, 
  365, 
  NOM_patients$time_to_event
)

# Urgent indicator
NOM_patients$urgent_event <- ifelse(NOM_patients$status365 == 2, 1, 0)

# Elective indicator
NOM_patients$elective_event <- ifelse(NOM_patients$status365 == 1, 1, 0)


# Urgent time: if urgent happened, keep time; else censor at observed time
NOM_patients$urgent_time <- ifelse(NOM_patients$urgent_event == 1,
                                   NOM_patients$time_to_event,
                                   NOM_patients$time_to_event)

# Elective time: if elective happened, keep time; else censor at observed time
NOM_patients$elective_time <- ifelse(NOM_patients$elective_event == 1,
                                     NOM_patients$time_to_event,
                                     NOM_patients$time_to_event)

NOM_patients$status <- factor(NOM_patients$status, 0:2, c("None", "Elective", "Urgent/Emergent"))

NOM_patients$any_appy <- ifelse(NOM_patients$status365 != 0, 1, 0)

```

Time to Urgent, Elective, and OVerall Appendectomy
```{r}

library(ggsurvfit)
library(broom)
library(ggplot2)

#survival curves for each type
urgent_appy <- survfit2(Surv(time_to_event, urgent_event) ~ 1, data = NOM_patients)
elective_appy <- survfit2(Surv(time_to_event, elective_event) ~ 1, data = NOM_patients)
all_appy <- survfit2(Surv(time_to_event, any_appy) ~ 1, data = NOM_patients)

urgent_df <- broom::tidy(urgent_appy)
elective_df <- broom::tidy(elective_appy)
all_df <- broom::tidy(all_appy)

#overall cumulative risk plot
plot_all <- ggsurvfit(all_appy, type = "risk") +
  labs(x = "Days Since Index Treatment with Antibiotics",
       y = "Cumulative Incidence of Appendectomy",
       title = "Risk of Appendectomy After Antibiotics-First Treatment") +
  scale_x_continuous(breaks = c(0, 30, 90, 180, 270, 365)) +
  ylim(0, 0.5) +
  add_confidence_interval(fill = "black", alpha = 0.3)
plot_all

# Add elective + urgent risks
plot_combined <- plot_all +
  geom_step(data = urgent_df, aes(x = time, y = 1 - estimate, color = "Urgent", linetype = "Urgent"), size = 0.6) +
  geom_step(data = elective_df, aes(x = time, y = 1 - estimate, color = "Elective", linetype = "Elective"), size = 0.6) +
  geom_step(data = all_df, aes(x = time, y = 1 - estimate, color = "Overall", linetype = "Overall"), size = 0.6) +

  geom_ribbon(data = urgent_df,
              aes(x = time, ymin = 1 - conf.high, ymax = 1 - conf.low),
              fill = "#d62728", alpha = 0.3) +
  geom_ribbon(data = elective_df,
              aes(x = time, ymin = 1 - conf.high, ymax = 1 - conf.low),
              fill = "#1f77b4", alpha = 0.3) +

  scale_color_manual(values = c("Elective" = "#1f77b4",
                                "Urgent" = "#d62728",
                                "Overall" = "black")) +
  scale_linetype_manual(values = c("Elective" = "dashed",
                                   "Urgent" = "twodash",
                                   "Overall" = "solid")) +  
  theme_classic() +
  labs(color = "Appendectomy Type", linetype = "Appendectomy Type")

print(plot_combined)

ggsave(
  filename = "risk_plot.png",  # file name
  plot = plot_combined,                    
  width = 8,                               
  height = 6,                              
  dpi = 300                               
)

```

Plot of Stratified by Appendicolith vs No Appendicolith
```{r}
#unstratified by appendicolith presence
all_appy <- survfit2(Surv(time_to_event, any_appy) ~ 1, data = NOM_patients)
all_df <- broom::tidy(all_appy)
#stratified by appendicolith presence
stratified_fit <- survfit2(Surv(time_to_event, any_appy) ~ appendicolithoutcomes, data = NOM_patients)
strat_df <- broom::tidy(stratified_fit)

plot_strat <- ggsurvfit(stratified_fit, type = "risk") +
  labs(x = "Days Since Index Treatment with Antibiotics",
       y = "Cumulative Incidence of Appendectomy",
       title = "Risk of Appendectomy After Antibiotics-First Treatment") +
  scale_x_continuous(breaks = c(0, 30, 90, 180, 270, 365))


#plotting stratified plots
plot_combined <- plot_strat +
  geom_step(
    data = all_df,
    aes(x = time, y = 1 - estimate, color = "Overall"),
    linewidth = 0.6
  ) + 
  scale_color_manual(
    name = "Appendicolith Status",
    values = c(
      "0" = "#1f77b4",
      "1" = "#d62728",
      "Overall" = "black"
    ), 
    labels = c(
      "0" = "Absent", 
      "1" = "Present", 
      "Overall" = "Overall"
    )
  ) +  
scale_y_continuous(limits = c(0, 0.5), label = scales::label_percent()) + 
  theme_classic() + 
  geom_point(aes(x = 30, y = 0.2)) +
annotate("text", x = 30, y = 0.23, label = "30-Day \n Overall CODA Rate:\n 20% [17-23]", size = 2.5) +
  geom_point(aes(x = 90, y = 0.29)) +
annotate("text", x = 90, y = 0.325, label = "90-Day \n Overall CODA Rate:\n 29% [26-32]", size = 2.5) 


print(plot_combined)

ggsave(
  filename = "stratified_risk_plot.png",  # file name
  plot = plot_combined,                     
  width = 8,                                
  height = 6,                              
  dpi = 300                                
)


```




## Setting up data for Kaplan Meier time to appendicitis symptoms
```{r, echo = FALSE, message = FALSE, warning = FALSE}

NOM_patients$ed_ret_dateoutcomes[
  NOM_patients$ed_ret_dateoutcomes == ""
] <- NA

NOM_patients$ed_ret_dateoutcomes <- ymd(NOM_patients$ed_ret_dateoutcomes)


#creating variable that is time in days from NOM decision to appy
NOM_patients$time_to_EDsymptoms <- NOM_patients$ed_ret_dateoutcomes - NOM_patients$time_of_dxoutcomes



NOM_patients$time_to_ED <- ifelse(
  is.na(NOM_patients$time_to_EDsymptoms),
  365,
  NOM_patients$time_to_EDsymptoms
)
#administratively censoring those beyond 1 year
NOM_patients$ED_status <- ifelse(
  NOM_patients$time_to_ED > 365, 
  0, #administratively censored beyond 1 year
  NOM_patients$ed_return_365outcomes
)

#if reason for ED visit is 1 (cont. or worsening physical symptoms) or 2 (recurrence of symptoms) then it still equals 1, else 0
NOM_patients$ED_status <- ifelse(
  NOM_patients$ED_status == 1 & (NOM_patients$ed_reasonoutcomes == 1 | NOM_patients$ed_reasonoutcomes == 2),
  1, 
  0)

table(NOM_patients$ED_status)

table(NOM_patients$ED_status, NOM_patients$status365)


#Should we show percentage of those who came back w/ symptoms but didn't get appendectomy?
```

#Plot of Time to Appendicitis symptoms
```{r, echo = FALSE, message = FALSE, warning = FALSE}
ed_fit <- survfit(Surv(time_to_ED, ED_status) ~ 1, data = NOM_patients, conf.type = "log-log")


ed_plot <- ggsurvfit(ed_fit, type = "risk", color = "#d62728") +
  labs(x = "Days Since Index Treatment with Antibiotics",
       y = "Cumulative Incidence of Symptom-Driven ED Visit",
       title = "Risk of Symptom-Driven ED Visit After Antibiotics-First Treatment") +
  scale_x_continuous(breaks = c(0, 30, 90, 180, 270, 365)) +
  ylim(0, 0.4) +
  xlim(0, 365) +
  add_confidence_interval(fill = "#d62728", alpha = 0.3) + 
  theme_classic()

ed_plot

ggsave(
  filename = "ed_plot.png",  # file name
  plot = ed_plot,                     
  width = 8,                                
  height = 6,                              
  dpi = 300                                
)

```
